### PR TITLE
Bump rust to 1.81

### PR DESCRIPTION
**Pull request by Nothing4You**
- https://github.com/LemmyNet/lemmy/pull/5032
- https://github.com/LemmyNet/lemmy/issues/5159

### CODE REVIEW

**Comment by raskyld** [comment]
Hey, thanks a lot!

**Comment by dessalines** [comment]
This also needs a release too.

**Comment by raskyld** [comment]
You are right! Done :)

**Comment by dessalines** [comment]
Thx!

**Pull request merged**
